import Head from 'next/head'
import { useMoralis } from 'react-moralis';
import Login from '../components/Login'

export default function Home() {
  const { isAuthenticated, logout } = useMoralis();

  if(!isAuthenticated) return <Login />;

  return (
    <div className="">
      <Head>
        <title>Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Welcome to METAVERSE</h1>
      <button onClick={logout} >Logout</button>      

    </div>
  )
}
